// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZWZCGHAIKy4vzCeWFl24Ie2SJwswmxA',
    appId: '1:817784700049:web:90a0585b093aed45745330',
    messagingSenderId: '817784700049',
    projectId: 'flutterworkelectric',
    authDomain: 'flutterworkelectric.firebaseapp.com',
    storageBucket: 'flutterworkelectric.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsCzyb0izIRV8ZAZz4UF_PuXgLg3gg8M',
    appId: '1:817784700049:android:6b253b5d7fa6b1e1745330',
    messagingSenderId: '817784700049',
    projectId: 'flutterworkelectric',
    storageBucket: 'flutterworkelectric.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqVMH84NRRy9N8wNNM2t2MocEsmIgym2A',
    appId: '1:817784700049:ios:10efe9974092292d745330',
    messagingSenderId: '817784700049',
    projectId: 'flutterworkelectric',
    storageBucket: 'flutterworkelectric.firebasestorage.app',
    iosBundleId: 'com.example.electricpayment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqVMH84NRRy9N8wNNM2t2MocEsmIgym2A',
    appId: '1:817784700049:ios:10efe9974092292d745330',
    messagingSenderId: '817784700049',
    projectId: 'flutterworkelectric',
    storageBucket: 'flutterworkelectric.firebasestorage.app',
    iosBundleId: 'com.example.electricpayment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZWZCGHAIKy4vzCeWFl24Ie2SJwswmxA',
    appId: '1:817784700049:web:3b75732b9b9483e0745330',
    messagingSenderId: '817784700049',
    projectId: 'flutterworkelectric',
    authDomain: 'flutterworkelectric.firebaseapp.com',
    storageBucket: 'flutterworkelectric.firebasestorage.app',
  );

}